export const SET_CATEGORY = 'SET_CATEGORY'
export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_BY_CATEGORY = 'GET_PRODUCT_BY_CATEGORY'
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'